version: '3.4'

# Extract logs out
services:
    jira:
        image: blacklabelops/jira:7.12.1
        env_file:
            - .jira.env
        networks:
            - jiranet
            - postgresnet
        depends_on:
            - postgresql
            - postfix
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - jiradata:/var/atlassian/jira
            - ./backups:/var/atlassian/jira/export

    postgresql:
        image: postgres:9.6.9-alpine
        env_file:
            - .postgres.env
        networks:
            - postgresnet
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - postgresqldata:/var/lib/postgresql/data

    # Front App
    nginx:
        image: blacklabelops/nginx
        depends_on:
            - jira
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - letsencrypt_certs:/etc/letsencrypt
            - letsencrypt_challenges:/var/www/letsencrypt
        networks:
            jiranet:
                aliases:
                    - "${JIRA_PROXY_NAME:-jira.example.ru}"
        ports:
            - '80:80'
            - '443:443'
        env_file:
            - .nginx.env

    letsencrypt:
        image: blacklabelops/letsencrypt
        depends_on:
            - nginx
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - letsencrypt_certs:/etc/letsencrypt
            - letsencrypt_challenges:/var/www/letsencrypt
        env_file:
            - .letsencrypt.env

    cron:
        image: blacklabelops/jobber:docker
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /var/run/docker.sock:/var/run/docker.sock
        env_file:
          - .cron.env

    postfix:
        image: juanluisbaptiste/postfix:latest
        networks:
            - jiranet
        restart: unless-stopped
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        env_file:
            - .smtp.env

volumes:
    jiradata:
        external: false
    postgresqldata:
        external: false
    letsencrypt_challenges:
        external: false
    letsencrypt_certs:
        external: false
        name: letsencrypt_certs


networks:
    jiranet:
        driver: bridge
    postgresnet:
        driver: bridge

